version: '3.8'


services:

  postgres-user:
    image: postgres:14
    container_name: postgres-user
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: useradmin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - backend

  postgres-budget:
    image: postgres:14
    container_name: postgres-budget
    environment:
      POSTGRES_DB: budgetdb
      POSTGRES_USER: budgetadmin
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    networks:
      - backend

  mongo-expense:
    image: mongo:6
    container_name: mongo-expense
    ports:
      - "27017:27017"
    networks:
      - backend
    volumes:
      - mongo_expense_data:/data/db

networks:
  backend:

volumes:
  mongo_expense_data:

